<?php
/**
 * PetDtoApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Bankiru\PetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hello API Platform
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bankiru\PetClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Bankiru\PetClient\ApiException;
use Bankiru\PetClient\Configuration;
use Bankiru\PetClient\HeaderSelector;
use Bankiru\PetClient\ObjectSerializer;

/**
 * PetDtoApi Class Doc Comment
 *
 * @category Class
 * @package  Bankiru\PetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PetDtoApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiPetIdDelete' => [
            'application/json',
        ],
        'apiPetIdGet' => [
            'application/json',
        ],
        'apiPetcreatePost' => [
            'application/ld+json',
            'application/json',
            'text/html',
        ],
        'apiPetsGetCollection' => [
            'application/json',
        ],
        'apiPetupdatePut' => [
            'application/ld+json',
            'application/json',
            'text/html',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiPetIdDelete
     *
     * Removes the PetDto resource.
     *
     * @param  string $id Pet identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetIdDelete'] to see the possible values for this operation
     *
     * @throws \Bankiru\PetClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiPetIdDelete($id, string $contentType = self::contentTypes['apiPetIdDelete'][0])
    {
        $this->apiPetIdDeleteWithHttpInfo($id, $contentType);
    }

    /**
     * Operation apiPetIdDeleteWithHttpInfo
     *
     * Removes the PetDto resource.
     *
     * @param  string $id Pet identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetIdDelete'] to see the possible values for this operation
     *
     * @throws \Bankiru\PetClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiPetIdDeleteWithHttpInfo($id, string $contentType = self::contentTypes['apiPetIdDelete'][0])
    {
        $request = $this->apiPetIdDeleteRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiPetIdDeleteAsync
     *
     * Removes the PetDto resource.
     *
     * @param  string $id Pet identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiPetIdDeleteAsync($id, string $contentType = self::contentTypes['apiPetIdDelete'][0])
    {
        return $this->apiPetIdDeleteAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiPetIdDeleteAsyncWithHttpInfo
     *
     * Removes the PetDto resource.
     *
     * @param  string $id Pet identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiPetIdDeleteAsyncWithHttpInfo($id, string $contentType = self::contentTypes['apiPetIdDelete'][0])
    {
        $returnType = '';
        $request = $this->apiPetIdDeleteRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiPetIdDelete'
     *
     * @param  string $id Pet identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiPetIdDeleteRequest($id, string $contentType = self::contentTypes['apiPetIdDelete'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling apiPetIdDelete'
            );
        }


        $resourcePath = '/api/v2/pet/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiPetIdGet
     *
     * Retrieves a PetDto resource.
     *
     * @param  string $id PetDto identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetIdGet'] to see the possible values for this operation
     *
     * @throws \Bankiru\PetClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bankiru\PetClient\Model\PetDtoJsonldRead
     */
    public function apiPetIdGet($id, string $contentType = self::contentTypes['apiPetIdGet'][0])
    {
        list($response) = $this->apiPetIdGetWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation apiPetIdGetWithHttpInfo
     *
     * Retrieves a PetDto resource.
     *
     * @param  string $id PetDto identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetIdGet'] to see the possible values for this operation
     *
     * @throws \Bankiru\PetClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bankiru\PetClient\Model\PetDtoJsonldRead, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiPetIdGetWithHttpInfo($id, string $contentType = self::contentTypes['apiPetIdGet'][0])
    {
        $request = $this->apiPetIdGetRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Bankiru\PetClient\Model\PetDtoJsonldRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Bankiru\PetClient\Model\PetDtoJsonldRead' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Bankiru\PetClient\Model\PetDtoJsonldRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Bankiru\PetClient\Model\PetDtoJsonldRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bankiru\PetClient\Model\PetDtoJsonldRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiPetIdGetAsync
     *
     * Retrieves a PetDto resource.
     *
     * @param  string $id PetDto identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiPetIdGetAsync($id, string $contentType = self::contentTypes['apiPetIdGet'][0])
    {
        return $this->apiPetIdGetAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiPetIdGetAsyncWithHttpInfo
     *
     * Retrieves a PetDto resource.
     *
     * @param  string $id PetDto identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiPetIdGetAsyncWithHttpInfo($id, string $contentType = self::contentTypes['apiPetIdGet'][0])
    {
        $returnType = '\Bankiru\PetClient\Model\PetDtoJsonldRead';
        $request = $this->apiPetIdGetRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiPetIdGet'
     *
     * @param  string $id PetDto identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiPetIdGetRequest($id, string $contentType = self::contentTypes['apiPetIdGet'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling apiPetIdGet'
            );
        }


        $resourcePath = '/api/v2/pet/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', 'text/html', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiPetcreatePost
     *
     * Creates a PetDto resource.
     *
     * @param  \Bankiru\PetClient\Model\PetDtoJsonldWritePatch $petDtoJsonldWritePatch The new PetDto resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetcreatePost'] to see the possible values for this operation
     *
     * @throws \Bankiru\PetClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bankiru\PetClient\Model\PetDtoJsonldRead
     */
    public function apiPetcreatePost($petDtoJsonldWritePatch, string $contentType = self::contentTypes['apiPetcreatePost'][0])
    {
        list($response) = $this->apiPetcreatePostWithHttpInfo($petDtoJsonldWritePatch, $contentType);
        return $response;
    }

    /**
     * Operation apiPetcreatePostWithHttpInfo
     *
     * Creates a PetDto resource.
     *
     * @param  \Bankiru\PetClient\Model\PetDtoJsonldWritePatch $petDtoJsonldWritePatch The new PetDto resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetcreatePost'] to see the possible values for this operation
     *
     * @throws \Bankiru\PetClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bankiru\PetClient\Model\PetDtoJsonldRead, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiPetcreatePostWithHttpInfo($petDtoJsonldWritePatch, string $contentType = self::contentTypes['apiPetcreatePost'][0])
    {
        $request = $this->apiPetcreatePostRequest($petDtoJsonldWritePatch, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\Bankiru\PetClient\Model\PetDtoJsonldRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Bankiru\PetClient\Model\PetDtoJsonldRead' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Bankiru\PetClient\Model\PetDtoJsonldRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Bankiru\PetClient\Model\PetDtoJsonldRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bankiru\PetClient\Model\PetDtoJsonldRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiPetcreatePostAsync
     *
     * Creates a PetDto resource.
     *
     * @param  \Bankiru\PetClient\Model\PetDtoJsonldWritePatch $petDtoJsonldWritePatch The new PetDto resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetcreatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiPetcreatePostAsync($petDtoJsonldWritePatch, string $contentType = self::contentTypes['apiPetcreatePost'][0])
    {
        return $this->apiPetcreatePostAsyncWithHttpInfo($petDtoJsonldWritePatch, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiPetcreatePostAsyncWithHttpInfo
     *
     * Creates a PetDto resource.
     *
     * @param  \Bankiru\PetClient\Model\PetDtoJsonldWritePatch $petDtoJsonldWritePatch The new PetDto resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetcreatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiPetcreatePostAsyncWithHttpInfo($petDtoJsonldWritePatch, string $contentType = self::contentTypes['apiPetcreatePost'][0])
    {
        $returnType = '\Bankiru\PetClient\Model\PetDtoJsonldRead';
        $request = $this->apiPetcreatePostRequest($petDtoJsonldWritePatch, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiPetcreatePost'
     *
     * @param  \Bankiru\PetClient\Model\PetDtoJsonldWritePatch $petDtoJsonldWritePatch The new PetDto resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetcreatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiPetcreatePostRequest($petDtoJsonldWritePatch, string $contentType = self::contentTypes['apiPetcreatePost'][0])
    {

        // verify the required parameter 'petDtoJsonldWritePatch' is set
        if ($petDtoJsonldWritePatch === null || (is_array($petDtoJsonldWritePatch) && count($petDtoJsonldWritePatch) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $petDtoJsonldWritePatch when calling apiPetcreatePost'
            );
        }


        $resourcePath = '/api/v2/pet/create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', 'text/html', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($petDtoJsonldWritePatch)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($petDtoJsonldWritePatch));
            } else {
                $httpBody = $petDtoJsonldWritePatch;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiPetsGetCollection
     *
     * Retrieves the collection of PetDto resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $itemsPerPage The number of items per page (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetsGetCollection'] to see the possible values for this operation
     *
     * @throws \Bankiru\PetClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bankiru\PetClient\Model\ApiPetsGetCollection200Response
     */
    public function apiPetsGetCollection($page = 1, $itemsPerPage = 10, string $contentType = self::contentTypes['apiPetsGetCollection'][0])
    {
        list($response) = $this->apiPetsGetCollectionWithHttpInfo($page, $itemsPerPage, $contentType);
        return $response;
    }

    /**
     * Operation apiPetsGetCollectionWithHttpInfo
     *
     * Retrieves the collection of PetDto resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $itemsPerPage The number of items per page (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetsGetCollection'] to see the possible values for this operation
     *
     * @throws \Bankiru\PetClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bankiru\PetClient\Model\ApiPetsGetCollection200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiPetsGetCollectionWithHttpInfo($page = 1, $itemsPerPage = 10, string $contentType = self::contentTypes['apiPetsGetCollection'][0])
    {
        $request = $this->apiPetsGetCollectionRequest($page, $itemsPerPage, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Bankiru\PetClient\Model\ApiPetsGetCollection200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Bankiru\PetClient\Model\ApiPetsGetCollection200Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Bankiru\PetClient\Model\ApiPetsGetCollection200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Bankiru\PetClient\Model\ApiPetsGetCollection200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bankiru\PetClient\Model\ApiPetsGetCollection200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiPetsGetCollectionAsync
     *
     * Retrieves the collection of PetDto resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $itemsPerPage The number of items per page (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetsGetCollection'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiPetsGetCollectionAsync($page = 1, $itemsPerPage = 10, string $contentType = self::contentTypes['apiPetsGetCollection'][0])
    {
        return $this->apiPetsGetCollectionAsyncWithHttpInfo($page, $itemsPerPage, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiPetsGetCollectionAsyncWithHttpInfo
     *
     * Retrieves the collection of PetDto resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $itemsPerPage The number of items per page (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetsGetCollection'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiPetsGetCollectionAsyncWithHttpInfo($page = 1, $itemsPerPage = 10, string $contentType = self::contentTypes['apiPetsGetCollection'][0])
    {
        $returnType = '\Bankiru\PetClient\Model\ApiPetsGetCollection200Response';
        $request = $this->apiPetsGetCollectionRequest($page, $itemsPerPage, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiPetsGetCollection'
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $itemsPerPage The number of items per page (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetsGetCollection'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiPetsGetCollectionRequest($page = 1, $itemsPerPage = 10, string $contentType = self::contentTypes['apiPetsGetCollection'][0])
    {


        if ($itemsPerPage !== null && $itemsPerPage < 0) {
            throw new \InvalidArgumentException('invalid value for "$itemsPerPage" when calling PetDtoApi.apiPetsGetCollection, must be bigger than or equal to 0.');
        }
        

        $resourcePath = '/api/v2/pets';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $itemsPerPage,
            'itemsPerPage', // param base name
            'integer', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', 'text/html', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiPetupdatePut
     *
     * Replaces the PetDto resource.
     *
     * @param  \Bankiru\PetClient\Model\PetDtoJsonldPut $petDtoJsonldPut The updated PetDto resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetupdatePut'] to see the possible values for this operation
     *
     * @throws \Bankiru\PetClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bankiru\PetClient\Model\PetDtoJsonldRead
     */
    public function apiPetupdatePut($petDtoJsonldPut, string $contentType = self::contentTypes['apiPetupdatePut'][0])
    {
        list($response) = $this->apiPetupdatePutWithHttpInfo($petDtoJsonldPut, $contentType);
        return $response;
    }

    /**
     * Operation apiPetupdatePutWithHttpInfo
     *
     * Replaces the PetDto resource.
     *
     * @param  \Bankiru\PetClient\Model\PetDtoJsonldPut $petDtoJsonldPut The updated PetDto resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetupdatePut'] to see the possible values for this operation
     *
     * @throws \Bankiru\PetClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bankiru\PetClient\Model\PetDtoJsonldRead, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiPetupdatePutWithHttpInfo($petDtoJsonldPut, string $contentType = self::contentTypes['apiPetupdatePut'][0])
    {
        $request = $this->apiPetupdatePutRequest($petDtoJsonldPut, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Bankiru\PetClient\Model\PetDtoJsonldRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Bankiru\PetClient\Model\PetDtoJsonldRead' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Bankiru\PetClient\Model\PetDtoJsonldRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Bankiru\PetClient\Model\PetDtoJsonldRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bankiru\PetClient\Model\PetDtoJsonldRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiPetupdatePutAsync
     *
     * Replaces the PetDto resource.
     *
     * @param  \Bankiru\PetClient\Model\PetDtoJsonldPut $petDtoJsonldPut The updated PetDto resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetupdatePut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiPetupdatePutAsync($petDtoJsonldPut, string $contentType = self::contentTypes['apiPetupdatePut'][0])
    {
        return $this->apiPetupdatePutAsyncWithHttpInfo($petDtoJsonldPut, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiPetupdatePutAsyncWithHttpInfo
     *
     * Replaces the PetDto resource.
     *
     * @param  \Bankiru\PetClient\Model\PetDtoJsonldPut $petDtoJsonldPut The updated PetDto resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetupdatePut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiPetupdatePutAsyncWithHttpInfo($petDtoJsonldPut, string $contentType = self::contentTypes['apiPetupdatePut'][0])
    {
        $returnType = '\Bankiru\PetClient\Model\PetDtoJsonldRead';
        $request = $this->apiPetupdatePutRequest($petDtoJsonldPut, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiPetupdatePut'
     *
     * @param  \Bankiru\PetClient\Model\PetDtoJsonldPut $petDtoJsonldPut The updated PetDto resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiPetupdatePut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiPetupdatePutRequest($petDtoJsonldPut, string $contentType = self::contentTypes['apiPetupdatePut'][0])
    {

        // verify the required parameter 'petDtoJsonldPut' is set
        if ($petDtoJsonldPut === null || (is_array($petDtoJsonldPut) && count($petDtoJsonldPut) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $petDtoJsonldPut when calling apiPetupdatePut'
            );
        }


        $resourcePath = '/api/v2/pet/update';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', 'text/html', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($petDtoJsonldPut)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($petDtoJsonldPut));
            } else {
                $httpBody = $petDtoJsonldPut;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
