<?php
/**
 * ApiPetsGetCollection200ResponseHydraViewTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Bankiru\PetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hello API Platform
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bankiru\PetClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ApiPetsGetCollection200ResponseHydraViewTest Class Doc Comment
 *
 * @category    Class
 * @description ApiPetsGetCollection200ResponseHydraView
 * @package     Bankiru\PetClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApiPetsGetCollection200ResponseHydraViewTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ApiPetsGetCollection200ResponseHydraView"
     */
    public function testApiPetsGetCollection200ResponseHydraView()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "atId"
     */
    public function testPropertyAtId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "atType"
     */
    public function testPropertyAtType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydrafirst"
     */
    public function testPropertyHydrafirst()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydralast"
     */
    public function testPropertyHydralast()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydraprevious"
     */
    public function testPropertyHydraprevious()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydranext"
     */
    public function testPropertyHydranext()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
