<?php
/**
 * ApiPetsGetCollection200ResponseHydraSearchTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Bankiru\PetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hello API Platform
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bankiru\PetClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ApiPetsGetCollection200ResponseHydraSearchTest Class Doc Comment
 *
 * @category    Class
 * @description ApiPetsGetCollection200ResponseHydraSearch
 * @package     Bankiru\PetClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApiPetsGetCollection200ResponseHydraSearchTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ApiPetsGetCollection200ResponseHydraSearch"
     */
    public function testApiPetsGetCollection200ResponseHydraSearch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "atType"
     */
    public function testPropertyAtType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydratemplate"
     */
    public function testPropertyHydratemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydravariableRepresentation"
     */
    public function testPropertyHydravariableRepresentation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydramapping"
     */
    public function testPropertyHydramapping()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
