<?php
/**
 * ApiUsersGetCollection200ResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Bankiru\PetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hello API Platform
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bankiru\PetClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ApiUsersGetCollection200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ApiUsersGetCollection200Response
 * @package     Bankiru\PetClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApiUsersGetCollection200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ApiUsersGetCollection200Response"
     */
    public function testApiUsersGetCollection200Response()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydramember"
     */
    public function testPropertyHydramember()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydratotalItems"
     */
    public function testPropertyHydratotalItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydraview"
     */
    public function testPropertyHydraview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydrasearch"
     */
    public function testPropertyHydrasearch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
