<?php
/**
 * PetDtoApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Bankiru\PetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hello API Platform
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Bankiru\PetClient\Test\Api;

use \Bankiru\PetClient\Configuration;
use \Bankiru\PetClient\ApiException;
use \Bankiru\PetClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PetDtoApiTest Class Doc Comment
 *
 * @category Class
 * @package  Bankiru\PetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PetDtoApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiPetIdDelete
     *
     * Removes the PetDto resource..
     *
     */
    public function testApiPetIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPetIdGet
     *
     * Retrieves a PetDto resource..
     *
     */
    public function testApiPetIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPetcreatePost
     *
     * Creates a PetDto resource..
     *
     */
    public function testApiPetcreatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPetsGetCollection
     *
     * Retrieves the collection of PetDto resources..
     *
     */
    public function testApiPetsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPetupdatePut
     *
     * Replaces the PetDto resource..
     *
     */
    public function testApiPetupdatePut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
