<?php
/**
 * UserDtoApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Bankiru\PetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hello API Platform
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Bankiru\PetClient\Test\Api;

use \Bankiru\PetClient\Configuration;
use \Bankiru\PetClient\ApiException;
use \Bankiru\PetClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserDtoApiTest Class Doc Comment
 *
 * @category Class
 * @package  Bankiru\PetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserDtoApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiUserIdDelete
     *
     * Removes the UserDto resource..
     *
     */
    public function testApiUserIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUserIdGet
     *
     * Retrieves a UserDto resource..
     *
     */
    public function testApiUserIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsercreatePost
     *
     * Creates a UserDto resource..
     *
     */
    public function testApiUsercreatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersGetCollection
     *
     * Retrieves the collection of UserDto resources..
     *
     */
    public function testApiUsersGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUserupdatePut
     *
     * Replaces the UserDto resource..
     *
     */
    public function testApiUserupdatePut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
